version: '2'
services:
    mentorcarpatin-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/MentorCarpatin/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=MentorCarpatin
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
